In [8]:
import numpy as np
np.__version__

'1.21.5'

# Creating 1D arrya using array function

In [17]:
a = np.array([1,2,3,4,5])
print(a)
print(a.dtype)
print(a.shape)
print(a.size)


[1 2 3 4 5]
int32
(5,)
5


# Creating 2D arrya using array function

In [18]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.dtype)
print(b.shape)
print(b.size)

[[1 2 3]
 [4 5 6]]
int32
(2, 3)
6


# Creating 3D arrya using array function

In [30]:
c =np.array(
        [
        [[1,2,3],[4,5,6]],
        [[7,8,9],[10,11,12]],
        [[13,14,15],[16,17,18]]
        ]
)
print(c)
print(c.dtype)
print(c.shape)
print(c.size)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
int32
(3, 2, 3)
18


# creating 1D array using arange function

In [32]:
d =np.arange(10)
print(d)
print(d.dtype)
print(d.shape)
print(d.size)

[0 1 2 3 4 5 6 7 8 9]
int32
(10,)
10


# creating 2D array using arange function

In [40]:
d =np.arange(18).reshape(9,2)
print(d)
print(d.dtype)
print(d.shape)
print(d.size)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]]
int32
(9, 2)
18


# creating 3D array using arange function

In [ ]:
e =np.arange(18).reshape(3,2,3)
print(e)
print(e.dtype)
print(e.shape)
print(e.size)

# creating array using ones  (1D)

In [54]:
f =np.ones(18)
f


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

# creating  ones array using (2D)

In [59]:
g =np.ones(18).reshape(2,9)
print(g)
print(g.dtype)
print(g.shape)
print(g.size)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
float64
(2, 9)
18


# creating  ones array using (3D)

In [62]:
h =np.ones(8).reshape(2,2,2)
h

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

# creating random num using 1D array

In [66]:
i =np.random.randint(20,size=10)
print (i)
print(i.dtype)
print(i.shape)


[ 5 17 17  3 16 19 14 18 10  3]
int32
(10,)


# creating random num using 2D array

In [72]:
j =np.random.randint(10,20,size=(5,6))
print(j)
print(j.dtype)
print(j.shape)


[[18 17 14 17 13 13]
 [11 17 15 10 13 19]
 [14 15 17 11 10 15]
 [11 11 17 16 19 13]
 [17 18 14 19 19 12]]
int32
(5, 6)


# creating random num using 3D array

In [77]:
k =np.random.randint(5,15,size =(3,2,3))
print(k)
print(k.dtype)
print(k.shape)
print(k.size)

[[[11  8  8]
  [ 7  8 10]]

 [[12  7 11]
  [ 5  5 14]]

 [[13  8 12]
  [ 7 13  5]]]
int32
(3, 2, 3)
18


# create array with single low multipal high

In [86]:
l =np.random.randint(5,[10,15,20,30,40])
print(l)
print(l.dtype)
print(l.shape)
print(l.size)

[ 8 12 11  8 36]
int32
(5,)
5


# create array with single high multipal low

In [89]:
m =np.random.randint([10,20,30],40)
print(m)
print(m.dtype)
print(m.shape)
print(m.size)

[19 22 37]
int32
(3,)
3


# creat array with multipal low multipal high

In [92]:
n =np.random.randint([1,2,3],[10,20,30])
print(n)
print(n.dtype)
print(n.shape)
print(n.size)

[3 5 3]
int32
(3,)
3
